name: tienda_virtual_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pdf: ^3.11.3
  printing: ^5.11.1
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  firebase_core: ^2.27.1
  cloud_firestore: ^4.16.0
  collection: ^1.19.1
  animate_do: ^3.0.2
  another_flushbar: ^1.12.30 # Versión sugerida de another_flushbar

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo-nuevo.png
  # Para agregar fuentes personalizadas:
  # fonts:
  #   - family: NombreDeTuFuente
  #     fonts:
  #       - asset: fonts/NombreDeTuFuente-Regular.ttf
  #       - asset: fonts/NombreDeTuFuente-Bold.ttf
  #         weight: 700
